### ISSUE TITLE
Data split

### ISSUE THREAD

**Issue by lev1ayz** [talshaharabany/AutoSAM#1]
Hi,

What split did you use for each dataset? Do you maybe have a split.txt file with the specific images/masks for each split for each dataset?

**Comment by talshaharabany** [comment]
Thank you for your inquiry. I have updated the repository with the necessary information regarding the dataset splits. Please take a look at the updated repository, and you should find the details you're looking for. If you have any further questions or need additional assistance, feel free to ask.

**Comment by lev1ayz** [comment]
Thank you!
